project: 
  type: website
  output-dir: docs

website:
  title: "Leonel Salazar"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Honeybee Project"
            file: Group 10 Final Project/manuscript_final-2.qmd

    right:
      - icon: github 
        href: https://leonel-salazar.github.io/My-Data      

format:
  html:
    theme: darkly
    highlight: tango
    css: styles.css
    toc: FALSE


