<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leonel Salazar">

<title>Leonel Salazar - Student Depression Analytis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Leonel Salazar</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../Group 10 Final Project/manuscript_final-2.html">
 <span class="dropdown-text">Honeybee Project</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Student Depression Project/student depression analysis.html">
 <span class="dropdown-text">Student Depression Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://leonel-salazar.github.io/My-Data"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Student Depression Analytis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Leonel Salazar </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  id Gender Age          City Profession Academic.Pressure Work.Pressure CGPA
1  2   Male  33 Visakhapatnam    Student                 5             0 8.97
2  8 Female  24     Bangalore    Student                 2             0 5.90
3 26   Male  31      Srinagar    Student                 3             0 7.03
4 30 Female  28      Varanasi    Student                 3             0 5.59
5 32 Female  25        Jaipur    Student                 4             0 8.13
6 33   Male  29          Pune    Student                 2             0 5.70
  Study.Satisfaction Job.Satisfaction      Sleep.Duration Dietary.Habits
1                  2                0         '5-6 hours'        Healthy
2                  5                0         '5-6 hours'       Moderate
3                  5                0 'Less than 5 hours'        Healthy
4                  2                0         '7-8 hours'       Moderate
5                  3                0         '5-6 hours'       Moderate
6                  3                0 'Less than 5 hours'        Healthy
   Degree Have.you.ever.had.suicidal.thoughts.. Work.Study.Hours
1 B.Pharm                                   Yes                3
2     BSc                                    No                3
3      BA                                    No                9
4     BCA                                   Yes                4
5  M.Tech                                   Yes                1
6     PhD                                    No                4
  Financial.Stress Family.History.of.Mental.Illness Depression
1              1.0                               No          1
2              2.0                              Yes          0
3              1.0                              Yes          0
4              5.0                              Yes          1
5              1.0                               No          0
6              1.0                               No          0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   27901 obs. of  18 variables:
 $ id                                   : int  2 8 26 30 32 33 52 56 59 62 ...
 $ Gender                               : chr  "Male" "Female" "Male" "Female" ...
 $ Age                                  : num  33 24 31 28 25 29 30 30 28 31 ...
 $ City                                 : chr  "Visakhapatnam" "Bangalore" "Srinagar" "Varanasi" ...
 $ Profession                           : chr  "Student" "Student" "Student" "Student" ...
 $ Academic.Pressure                    : num  5 2 3 3 4 2 3 2 3 2 ...
 $ Work.Pressure                        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CGPA                                 : num  8.97 5.9 7.03 5.59 8.13 5.7 9.54 8.04 9.79 8.38 ...
 $ Study.Satisfaction                   : num  2 5 5 2 3 3 4 4 1 3 ...
 $ Job.Satisfaction                     : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Sleep.Duration                       : chr  "'5-6 hours'" "'5-6 hours'" "'Less than 5 hours'" "'7-8 hours'" ...
 $ Dietary.Habits                       : chr  "Healthy" "Moderate" "Healthy" "Moderate" ...
 $ Degree                               : chr  "B.Pharm" "BSc" "BA" "BCA" ...
 $ Have.you.ever.had.suicidal.thoughts..: chr  "Yes" "No" "No" "Yes" ...
 $ Work.Study.Hours                     : num  3 3 9 4 1 4 1 0 12 2 ...
 $ Financial.Stress                     : chr  "1.0" "2.0" "1.0" "5.0" ...
 $ Family.History.of.Mental.Illness     : chr  "No" "Yes" "Yes" "Yes" ...
 $ Depression                           : int  1 0 0 1 0 0 0 0 1 1 ...
NULL</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confusion Matrix:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted     0     1
        0  9081  1900
        1  2484 14436</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Accuracy: 0.843"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sensitivity: 0.884"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Specificity: 0.785"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AUC: 0.915"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Odds Ratios:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                             (Intercept) 
                               0.4140814 
                              GenderMale 
                               1.0604371 
                                     Age 
                               0.8958115 
                       Academic.Pressure 
                               2.3090100 
                                    CGPA 
                               1.0615796 
                      Study.Satisfaction 
                               0.7858413 
                        Work.Study.Hours 
                               1.1227590 
                     Financial.Stress1.0 
                               0.1727618 
                     Financial.Stress2.0 
                               0.2555127 
                     Financial.Stress3.0 
                               0.4999881 
                     Financial.Stress4.0 
                               0.7922738 
                     Financial.Stress5.0 
                               1.5657520 
Have.you.ever.had.suicidal.thoughts..Yes 
                              12.3005101 
     Family.History.of.Mental.IllnessYes 
                               1.2719489 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% Confidence Intervals for Odds Ratios:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                               2.5 %     97.5 %
(Intercept)                               0.01890855  4.4452242
GenderMale                                0.98845991  1.1376599
Age                                       0.88923420  0.9024025
Academic.Pressure                         2.24446971  2.3760499
CGPA                                      1.03668260  1.0870954
Study.Satisfaction                        0.76564137  0.8065133
Work.Study.Hours                          1.11212349  1.1335354
Financial.Stress1.0                       0.01631793  3.7516510
Financial.Stress2.0                       0.02413702  5.5481963
Financial.Stress3.0                       0.04723902 10.8557104
Financial.Stress4.0                       0.07485769 17.2013944
Financial.Stress5.0                       0.14793378 33.9954227
Have.you.ever.had.suicidal.thoughts..Yes 11.41701752 13.2605834
Family.History.of.Mental.IllnessYes       1.18610520  1.3641044</code></pre>
</div>
</div>
</section>
<section id="odds-ratio-analysis-from-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="odds-ratio-analysis-from-logistic-regression">Odds Ratio Analysis from Logistic Regression</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Odds Ratio (OR)</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
<th>Significance (CI ≠ 1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>0.4141</td>
<td>0.0199</td>
<td>4.4452</td>
<td>No</td>
</tr>
<tr class="even">
<td>Gender (Male vs.&nbsp;Female)</td>
<td>1.0604</td>
<td>0.9885</td>
<td>1.1377</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Age (per year increase)</td>
<td>0.8958</td>
<td>0.8892</td>
<td>0.9024</td>
<td>Yes (protective)</td>
</tr>
<tr class="even">
<td>Academic Pressure</td>
<td>2.3090</td>
<td>2.2445</td>
<td>2.3760</td>
<td>Yes (risk ↑)</td>
</tr>
<tr class="odd">
<td>CGPA (per unit increase)</td>
<td>1.0616</td>
<td>1.0366</td>
<td>1.0870</td>
<td>Yes (risk ↑)</td>
</tr>
<tr class="even">
<td>Study Satisfaction</td>
<td>0.7858</td>
<td>0.7656</td>
<td>0.8065</td>
<td>Yes (protective)</td>
</tr>
<tr class="odd">
<td>Work‐Study Hours (per hour increase)</td>
<td>1.1228</td>
<td>1.1121</td>
<td>1.1335</td>
<td>Yes (risk ↑)</td>
</tr>
<tr class="even">
<td>Financial Stress = 1</td>
<td>0.1728</td>
<td>0.0163</td>
<td>3.7516</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Financial Stress = 2</td>
<td>0.2555</td>
<td>0.0241</td>
<td>5.5482</td>
<td>No</td>
</tr>
<tr class="even">
<td>Financial Stress = 3</td>
<td>0.4999</td>
<td>0.0472</td>
<td>10.8570</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Financial Stress = 4</td>
<td>0.7923</td>
<td>0.0749</td>
<td>17.2010</td>
<td>No</td>
</tr>
<tr class="even">
<td>Financial Stress = 5</td>
<td>1.5658</td>
<td>0.1479</td>
<td>33.9950</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Ever had suicidal thoughts (Yes vs.&nbsp;No)</td>
<td>12.3005</td>
<td>11.4172</td>
<td>13.2679</td>
<td>Yes (risk ↑)</td>
</tr>
<tr class="even">
<td>Family History of Mental Illness (Yes vs.&nbsp;No)</td>
<td>1.2719</td>
<td>1.1861</td>
<td>1.3641</td>
<td>Yes (risk ↑)</td>
</tr>
</tbody>
</table>
<section id="interpretations" class="level3">
<h3 class="anchored" data-anchor-id="interpretations">Interpretations</h3>
<ul>
<li><strong>Odds Ratio (OR):</strong>
<ul>
<li>Values greater than 1 indicate increased odds of the outcome for that predictor.<br>
</li>
<li>Values less than 1 indicate decreased odds (protective effect).</li>
</ul></li>
<li><strong>Significant Predictors:</strong>
<ul>
<li><strong>Risk Factors (OR &gt; 1 and statistically significant):</strong>
<ul>
<li><strong>Academic Pressure (OR = 2.31):</strong> Higher academic pressure increases the odds of the outcome.<br>
</li>
<li><strong>CGPA (OR = 1.06):</strong> Increases in CGPA are associated with slightly higher odds of the outcome.<br>
</li>
<li><strong>Work‐Study Hours (OR = 1.12):</strong> More work-study hours increase the odds.<br>
</li>
<li><strong>Ever had suicidal thoughts (OR = 12.30):</strong> Strongly increases the odds.<br>
</li>
<li><strong>Family History of Mental Illness (OR = 1.27):</strong> Increases the odds.</li>
</ul></li>
<li><strong>Protective Factors (OR &lt; 1 and statistically significant):</strong>
<ul>
<li><strong>Age (OR = 0.90):</strong> Older age decreases the odds.<br>
</li>
<li><strong>Study Satisfaction (OR = 0.79):</strong> Higher satisfaction is associated with lower odds.</li>
</ul></li>
</ul></li>
<li><strong>Non-significant Predictors:</strong>
<ul>
<li><strong>Gender (Male vs.&nbsp;Female) and Financial Stress levels (1 to 5):</strong> Their 95% confidence intervals include 1, implying no statistically significant effect.</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Shapiro-Wilk Test Results (on 5000 sample):"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals_sample
W = 0.97803, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Breusch-Pagan Test for Homoscedasticity:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  bp_model
BP = 0.3459, df = 1, p-value = 0.5564</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "df_clean already exists"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  model
DW = 2.0128, p-value = 0.858
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="diagnostic-plot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plot-analysis">Diagnostic Plot Analysis</h2>
<section id="visual-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="visual-diagnostics">Visual Diagnostics</h3>
<p>The diagnostic plots reveal:</p>
<ul>
<li><strong>Normal Q-Q Plot</strong>: Shows some deviation from normality at the tails<br>
</li>
<li><strong>Residuals vs Fitted</strong>: Shows relatively even spread around zero<br>
</li>
<li><strong>Scale-Location</strong>: Shows relatively constant spread of standardized residuals<br>
</li>
<li><strong>Distribution of Residuals</strong>: Shows approximate symmetry but with some deviation from normal distribution</li>
</ul>
</section>
<section id="key-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-findings">Key Findings</h3>
<ol type="1">
<li>While the residuals show some deviation from normality (as indicated by the Shapiro-Wilk test), this is common in large datasets and doesn’t necessarily invalidate our model.<br>
</li>
<li>The homoscedasticity assumption appears to be met (supported by the Breusch-Pagan test).<br>
</li>
<li>The diagnostic plots suggest that while there are some departures from ideal conditions, they’re not severe enough to invalidate the model’s conclusions.</li>
</ol>
</section>
</section>
<section id="impact-on-business-models" class="level2">
<h2 class="anchored" data-anchor-id="impact-on-business-models">Impact on Business Models</h2>
<p>Based on the diagnostic plots and model assumptions for the depression study, the findings can influence several business models:</p>
<ul>
<li><p><strong>Healthcare Platforms</strong>:<br>
The study’s insights may enable platforms offering mental health services to tailor interventions and predictive analytics, improving user outcomes through early detection and personalized therapy.</p></li>
<li><p><strong>Employee Wellness Programs</strong>:<br>
Organizations investing in employee wellness might leverage these findings to implement mental health initiatives, screen for potential risks, and proactively offer support to improve productivity and wellbeing.</p></li>
<li><p><strong>Education-Related Mental Health Services</strong>:<br>
Educational institutions and related service providers can develop targeted programs for student mental health support, using the model to identify high-risk groups and deploy timely preventive measures.</p></li>
<li><p><strong>Insurance and Managed Care Models</strong>:<br>
Insurers may incorporate these predictive models to design better mental health coverage plans and proactively manage the costs associated with mental health treatments.</p></li>
</ul>
<p>These business models can benefit from integrating predictive insights from the study, leading to improved service targeting, cost reduction, and enhanced overall outcomes.</p>
<p>Explanation of NRI:</p>
<p>The Net Reclassification Improvement (NRI) metric helps quantify how much a new model improves risk classification compared to a baseline model. Specifically, NRI measures the net proportion of individuals (both positive events, such as depressed cases, and negatives, such as non-depressed cases) that are correctly reclassified into higher or lower risk categories when a new predictor or set of predictors is added.</p>
<p>In practice:</p>
<p>For individuals with the event (e.g., depressed), the NRI is calculated as the percentage who move to a higher risk category minus the percentage who move to a lower risk category. For individuals without the event (e.g., not depressed), it is the percentage who move to a lower risk category minus the percentage who move to a higher risk category. The Total NRI is the sum of these two differences. An NRI value greater than 0 indicates that the new model has improved classification, while a negative NRI suggests a decline in performance, making it a useful measure for model comparison beyond traditional statistics like the AUC.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>$nri
[1] -0.02291923

$event_nri
[1] -0.01013514

$nonevent_nri
[1] -0.01278409

$events_reclassified
[1] 0.04391892

$nonevents_reclassified
[1] 0.03551136</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Detailed NRI Analysis:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Metric       Value
1                   Total NRI -0.01013514
2                   Event NRI -0.01013514
3               Non-event NRI  0.00000000
4     Events Reclassified (%)  4.39000000
5 Non-events Reclassified (%)  4.83000000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="student-depression-analysis_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Counts:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
11565 16336 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nPercentages:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
41.45 58.55 </code></pre>
</div>
</div>
<p>Total NRI = -0.0101:</p>
<p>The total NRI being slightly negative (about -1.01%) indicates that overall, the new model’s reclassification performance is marginally worse than the baseline when considering both events and non-events.</p>
<p>Event NRI = -0.0101:</p>
<p>The negative Event NRI (also about -1.01%) means that, for subjects who experienced the event, the new model actually reclassified them less accurately. In practical terms, there was a net downward shift for events (i.e., fewer events were moved to higher risk categories as desired).</p>
<p>Non-event NRI = 0.00:</p>
<p>A Non-event NRI of 0% suggests that for the subjects who did not experience the event, there was no net improvement in reclassification—neither a net gain nor loss in moving them to lower risk categories.</p>
<p>Events Reclassified = 1.39:</p>
<p>This value implies that only 1.39% of the events saw a change in their risk category under the new model. Given the negative Event NRI, this 1.39% change likely reflects an unfavorable direction (i.e., more events might have been reclassified to a lower risk category than desired).</p>
<p>Non-events Reclassified = 4.83:</p>
<p>Although 4.83% of non-events saw a reclassification (ideally shifting to a lower risk category), this positive reclassification did not impact the Non-event NRI, which remains 0.00. This indicates that the number of non-events reclassified correctly was balanced by those misclassified.</p>
<p>Summary:</p>
<p>While about 4.83% of non-events were reclassified (which is usually favorable), the overall benefit is negated by a small negative reclassification among events (1.39%), resulting in an overall negative Total NRI. In practical terms, the new model did not show a significant net benefit in reclassification compared to the baseline model.</p>
<p>Model Performance Summary Based on NRI Analysis</p>
<p>Overall NRI: The total NRI is -0.0101, indicating that, on balance, the new model performs marginally worse in risk reclassification compared to the baseline model. Event Reclassification: With an event NRI of -0.0101 and only 1.39% of events undergoing any category change, the new model shows a slight deterioration in correctly classifying individuals who experienced the event. Non-Event Reclassification: Although 4.83% of non-events were reclassified, the non-event NRI is 0.00, meaning that any potential reclassification benefits for non-events were fully offset by misclassifications. Implications: The marginally negative overall NRI suggests that the new model does not provide a clear benefit over the baseline when it comes to risk stratification. The findings point to the need for further refinement before the new model can be considered an improvement in accurately identifying risk levels among both events and non-events. Overall Model Performance Summary Based on NRI Analysis</p>
<p>The total NRI of -0.0101 indicates that the overall improvement in risk reclassification with the new model is slightly worse than the baseline. The event NRI of -0.0101 and the low events reclassified percentage (1.39%) suggest that the new model has a marginally negative impact on correctly classifying individuals who experienced the event. Although 4.83% of non-events were reclassified, the net non-event NRI is 0.00, meaning that the benefits for non-events are entirely offset by misclassifications. In summary, the new model does not exhibit a significant net benefit in risk reclassification compared to the baseline model, indicating that further refinement may be needed to achieve improved overall performance.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>